version: "3.8"

services:
  app:
    image: nihongo-tracker:latest
    ports:
      - "3000:3000"
    env_file:
      - Backend/.env
    depends_on:
      - mongo
    volumes:
      - ./Backend/.env:/app/Backend/.env:ro
    networks:
      - nginx_default

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nginx_default

volumes:
  mongo-data:

networks:
  nginx_default:
    external: true